### ISSUE TITLE
需求: 这个菜单能否自动发现并添加,手动太痛苦了

### ISSUE THREAD

**Issue by sucheasy** [txd-team/docsite#10]
如果顾虑到文档的先后顺序,可以自动发现,然后设置个排序值(基于时间或者手动设置),有需要的再手动改就行了....
我这个需求过分不?

**Comment by purple-force** [comment]
还有些文档归属类别的标题、不同归属类别的顺序等等，这些在markdown文件中定义，涉及到多个文件之间的分配协调，反而增加了开发的复杂度。考虑列出所有的菜单项，放置在一个文件中，供开发拷贝使用，你觉得怎样？

**Comment by sucheasy** [comment]
### 我基于我个人的理解提出以下两个场景
1. 博客 : 定期发布,时间倒序,注重新增及自动化展示
2. 手册 : 预先规划,不定时更新,注重文章排序与结构

对于我个人而言,两种场景最大的困难在于 json菜单的生成. 手动编制太容易导致格式出错.
docsite的目标是简单与易用,那么不能考虑太复杂的实现 我的想法如下:
> 场景1 文章按时间默认生成索引即可,文章内的跨目录引用 暂不做考虑  
> 场景2 按文件夹排序顺序生成目录排序即可(至于文件夹如何排序,让使用者操心就行了),所有文档的排序字段仅对当前目录生效.甚至文档也不定义排序字段,取文件结构的自然排序.

图片上传不上来,形如下图,直接取文件目录或者文件序列就行.如果想做的更加完善一些,那么就约定序号的格式,生成的时候直接去掉就可以了.至于间接导致的序号编排任务繁琐问题.可以设置默认值. 并按时间倒序排列即可.
```
 D:\WorkSpace\docsite\zh-cn\docs 的目录

18-10-12  19:02    <DIR>          .
18-10-12  19:02    <DIR>          ..
18-10-12  19:01    <DIR>          1.前言
18-10-06  07:52    <DIR>          2.快速开始
18-10-12  19:01    <DIR>          3.应用架构
18-10-12  19:02    <DIR>          4.部署手册
18-10-12  19:02    <DIR>          5.常见问题
```

**Comment by purple-force** [comment]
最大的问题在于采用这种方式后，如何确定中文版本和英文版本的对应关系。为方便进行目录的配置，在1.3.2版本中添加了生成md文件的相关元信息，在根目录的`md_json`文件夹中。对于博客的配置，会在近期实现自动编排功能，无需手动进行目录配置。

**Comment by khadgarmage** [comment]
@purple-force 这个没有解决吧？
