### ISSUE TITLE
安装报错-- docsite -v zsh: command not found: docsite

### ISSUE THREAD

**Issue by x-hacker** [txd-team/docsite#11]
安装过程：
➜  Cellar npm install docsite -g
npm WARN deprecated babel-preset-es2015@6.22.0: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
/usr/local/Cellar/node/10.11.0/bin/docsite -> /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/docsite.js

> fsevents@1.2.4 install /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.9.3 install /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/liliang11/.npm/node-sass/4.9.3/darwin-x64-64_binding.node

> node-sass@4.9.3 postinstall /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
+ docsite@1.2.2
added 610 packages from 689 contributors in 80.694s
============================================
本机的一些信息：
操作系统：Mac OS 10.14
node.js的版本信息：
➜  Cellar npm -v
6.4.1
➜  Cellar node -v
v10.11.0

**Comment by x-cold** [comment]
#12 这个 issue 是不是说明 #11 已经解决了呢

**Comment by x-hacker** [comment]
并没有解决...我是指定在docsite的bin目录里面执行: node docsite.js init 来运行的命令

**Comment by x-cold** [comment]
node.js 相关的环境变量是正常的吗，安装其他的命令行工具，比如 `create-react-app` 能正常运行不？

**Comment by x-cold** [comment]
@x-hacker 重新安装 node.js，问题已解决
