### ISSUE TITLE
运行docsite start报错

### ISSUE THREAD

**Issue by x-hacker** [txd-team/docsite#12]
报错的信息：
[23:48:21] Using gulpfile /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/gulpfile.js
[23:48:21] Starting 'webpack-dev-server'...
[23:48:22] Finished 'webpack-dev-server' after 90 ms
[23:48:22] Starting 'default'...
[23:48:22] Finished 'default' after 31 μs
[23:48:22] [webpack-dev-server] http://127.0.0.1:8080/webpack-dev-server/index.html
Hash: 3a210c0dc1eb165401fb
Version: webpack 2.7.0
Time: 152ms
           Asset     Size  Chunks  Chunk Names
         home.js  6.64 kB       0  home
documentation.js  6.61 kB       1  documentation
    community.js   6.6 kB       2  community
   blogDetail.js  6.61 kB       3  blogDetail
         blog.js  6.56 kB       4  blog
chunk    {0} home.js (home) 443 bytes [entry] [rendered]
    [4] ./src/pages/home/index.jsx 443 bytes {0} [built] [failed] [1 error]
chunk    {1} documentation.js (documentation) 398 bytes [entry] [rendered]
    [3] ./src/pages/documentation/index.jsx 398 bytes {1} [built] [failed] [1 error]
chunk    {2} community.js (community) 386 bytes [entry] [rendered]
    [2] ./src/pages/community/index.jsx 386 bytes {2} [built] [failed] [1 error]
chunk    {3} blogDetail.js (blogDetail) 389 bytes [entry] [rendered]
    [1] ./src/pages/blogDetail/index.jsx 389 bytes {3} [built] [failed] [1 error]
chunk    {4} blog.js (blog) 357 bytes [entry] [rendered]
    [0] ./src/pages/blog/index.jsx 357 bytes {4} [built] [failed] [1 error]

ERROR in ./src/pages/blog/index.jsx
Module parse failed: /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/src/pages/blog/index.jsx Unexpected token (20:6)
You may need an appropriate loader to handle this file type.
|     const blogs = dataSource.list;
|     return (
|       <div className="blog-list-page">
|         <Header
|           type="normal"

ERROR in ./src/pages/blogDetail/index.jsx
Module parse failed: /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/src/pages/blogDetail/index.jsx Unexpected token (88:6)
You may need an appropriate loader to handle this file type.
|     const __html = this.props.__html || this.state.__html;
|     return (
|       <div className="blog-detail-page">
|         <Header
|           type="normal"

ERROR in ./src/pages/community/index.jsx
Module parse failed: /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/src/pages/community/index.jsx Unexpected token (22:6)
You may need an appropriate loader to handle this file type.
|     const dataSource = communityConfig[language];
|     return (
|       <div className="community-page">
|         <Header
|           currentKey="community"

ERROR in ./src/pages/documentation/index.jsx
Module parse failed: /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/src/pages/documentation/index.jsx Unexpected token (94:6)
You may need an appropriate loader to handle this file type.
|     const __html = this.props.__html || this.state.__html;
|     return (
|       <div className="documentation-page">
|         <Header
|           currentKey="docs"

ERROR in ./src/pages/home/index.jsx
Module parse failed: /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/src/pages/home/index.jsx Unexpected token (42:6)
You may need an appropriate loader to handle this file type.
|     const headerLogo = headerType === 'primary' ? "/img/dubbo_white.png" : "/img/dubbo_colorful.png";
|     return (
|       <div className="home-page">
|         <section className="top-section">
|           <Header
webpack: Failed to compile.

**Comment by x-cold** [comment]
请确保 docsite init 生成的项目中的 npm 包全部安装好，然后再尝试一下；

另外麻烦附带上这几个文件的内容：

- .babelrc
- webpack.config.js
- package.json

**Comment by x-hacker** [comment]
抱歉，不是搞前端的，npm依赖这些搞不懂....

**Comment by x-hacker** [comment]
│   ├── y18n@3.2.1 deduped
│   └─┬ yargs-parser@4.2.1
│     └── camelcase@3.0.0 deduped
└── whatwg-fetch@2.0.4

npm ERR! peer dep missing: eslint-plugin-import@^1.16.0, required by eslint-config-ali@1.0.3
npm ERR! peer dep missing: eslint-plugin-react@^6.3.0, required by eslint-config-ali@1.0.3
npm ERR! invalid: react@15.6.2 /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/node_modules/react
npm ERR! invalid: react-dom@15.6.2 /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/node_modules/react-dom
npm ERR! invalid: react@15.6.2 /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/node_modules/react
npm ERR! invalid: react-dom@15.6.2 /usr/local/Cellar/node/10.11.0/lib/node_modules/docsite/bin/node_modules/react-dom


是因为存在这些 ERR嘛？

**Comment by x-cold** [comment]
是的 依赖需要重新安装，需要保证所有的依赖都完整安装成功哦

**Comment by x-hacker** [comment]
这三个文件的内容：
    .babelrc
    webpack.config.js
    package.json
====================
➜  bin cat .babelrc
{
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-object-rest-spread",
    "transform-object-assign",
    [
      "transform-runtime",
      {
        "helpers": false,
        "polyfill": false,
        "regenerator": true,
        "moduleName": "babel-runtime"
      }
    ]
  ],
  "presets": [
    "react",
    "stage-0",
    "es2015"
  ]
}

=================
➜  bin cat webpack.config.js
const path = require('path');
const fs = require('fs');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const entry = {};
const targetPath = path.join(__dirname, './src/pages');
fs.readdirSync(targetPath).forEach(page => {
  if (
    fs.statSync(path.join(targetPath, page)).isDirectory() &&
    fs.existsSync(path.join(targetPath, page, 'index.jsx'))
  ) {
    entry[page] = path.join(targetPath, page, 'index.jsx');
  }
});
module.exports = {
  entry,
  output: {
    path: path.join(__dirname, 'build'),
    filename: '[name].js',
  },
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  },
  module: {
    loaders: [
      {
        test: /\.js|jsx$/,
        exclude: [/node_modules/, /build\/lib/, /\.min\.js$/],
        use: 'babel-loader',
      },
      {
        test: /\.(s)?css$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader'],
        }),
      },
      {
        test: /\.json?$/,
        exclude: /node_modules/,
        use: 'json-loader',
      },
    ],
  },
  resolve: {
    extensions: ['.js', '.jsx', '.json'],
  },
  plugins: [
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new ExtractTextPlugin('[name].css'),
  ],
};

===================
➜  bin cat package.json
{
  "name": "site",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "docsite start",
    "build": "docsite build"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "6.23.1",
    "babel-eslint": "^6.0.5",
    "babel-loader": "6.4.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "6.22.0",
    "babel-preset-react": "6.23.0",
    "babel-preset-stage-0": "6.22.0",
    "babel-register": "^6.26.0",
    "css-loader": "0.6.12",
    "docsite": "^1.1.0",
    "eslint": "^3.19.0",
    "eslint-config-ali": "^1.0.0",
    "eslint-plugin-import": "^1.16.0",
    "eslint-plugin-react": "^6.3.0",
    "extract-text-webpack-plugin": "^2.1.2",
    "gulp": "3.9.1",
    "gulp-util": "2.2.20",
    "json-loader": "*",
    "node-libs-browser": "2.0.0",
    "node-sass": "^4.7.2",
    "opn": "^5.3.0",
    "raw-loader": "^0.5.1",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "sass-loader": "6.0.2",
    "style-loader": "0.6.5",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5"
  },
  "dependencies": {
    "classnames": "^2.2.5",
    "core-decorators": "^0.20.0",
    "js-cookie": "^2.2.0",
    "react-router": "^4.3.1",
    "react-scroll": "^1.7.10",
    "react-tilt": "^0.1.4",
    "whatwg-fetch": "^2.0.4"
  }
}

**Comment by x-cold** [comment]
升级一下 docsite 版本吧，目前 react 已经更新 16.5.2 了
