### ISSUE TITLE
build工程后，/build/home.css和/build/home.js在gitpage上会跳转到首页

### ISSUE THREAD

**Issue by MuSheng-0** [txd-team/docsite#16]
如题所示，导致首页UI无法显示。

**Comment by purple-force** [comment]
首页引用的资源是home.js和home.css，首页UI没法显示是什么意思？

**Comment by x-cold** [comment]
麻烦提供一下仓库地址，我们来看看

**Comment by MuSheng-0** [comment]
@x-cold @purple-force ,可能是git page的原因。上午刚创建工程，使用git page发布demo，刚刚午睡后再打开已经可以正常加载工程目录下编译后的build/home.css和build/home.js了。谢谢两位😀
