### ISSUE TITLE
在开发界面时添加别的组件，提示报错。

### ISSUE THREAD

**Issue by 1991wangliang** [txd-team/docsite#21]
想增加一个新的界面，界面中需要用到reactjs-pagination组件，当在界面中引用时报错。
![image](https://user-images.githubusercontent.com/5245347/53466044-3f659d80-3a8b-11e9-9c32-0dd1dc3c6d85.png)

但是这个组件已经安装到package下了。文件也能看到。

**Comment by 1991wangliang** [comment]
版本1.1.0+

**Comment by x-cold** [comment]
麻烦提供一个最小可复现的 demo 哈
