### ISSUE TITLE
需求：添加动态配置的功能

### ISSUE THREAD

**Issue by smk0621** [txd-team/docsite#22]
有的文档不需要社区功能，有的不需要博客功能，
希望”首页，社区，博客，文档“等，各个菜单功能可以拆分，需要时根据配置文件分别加入。

另外，动态生成zh-cn，en-us文件夹，并且在该文件夹下生成一堆静态文件的方式太冗余了，
如果要有十几个国家语言的情况呢？建议把国际化拆分出来。

**Comment by purple-force** [comment]
目前还不具备按需生成页面的功能。如果不需要的页面，可以在site_config/site.js中修改pageMenu，以去掉相关页面的入口。
关于第二点，一堆静态文件是不需要在开发过程中关注的。这些静态文件的作用是为了解决SEO的问题。另外，多语言放在一起统一管理，是为了方便语言切换时，能直接看到当前页面的不同语言版本。

**Comment by smk0621** [comment]
嗯，好的，感谢回答。
1. 
>目前还不具备按需生成页面的功能。如果不需要的页面，可以在site_config/site.js中修改pageMenu，
>以去掉相关页面的入口。
希望今后可以加入动态配置的改善。

2. 
>关于第二点，一堆静态文件是不需要在开发过程中关注的。这些静态文件的作用是为了解决SEO的问
>题。另外，多语言放在一起统一管理，是为了方便语言切换时，能直接看到当前页面的不同语言版本。
嗯，了解。是否能考虑增加像hexo一样的增加自动部署的功能，直接往git中deploy生成好的各种静态文件，因为每次手动拷贝都担心漏拷文件夹。
