### ISSUE TITLE
功能询问：如何增加包含md文件地址的链接

### ISSUE THREAD

**Issue by htynkn** [txd-team/docsite#23]
希望在docsite生成的网址上新增一个链接，内容为Edit on github page，链接内容到github对应的md文件。

也就是说不同的页面，能够根据github源md文件地址生成不同的链接。
以Dubbo网址为例，
在http://dubbo.incubator.apache.org/en-us/docs/user/preface/background.html 页面上，
这个链接应该指向
https://github.com/apache/incubator-dubbo-website/edit/asf-site/docs/en-us/user/preface/background.md

不知道docsite是否支持此类需求，如果支持具体要怎么修改？

**Comment by purple-force** [comment]
不建议这样做，原因如下：
1. docsite生成的站点静态文件是和github没有太大关联的，如果自动生成，需要额外指定github地址，对应的分支等信息
2.修改md文件后，必须经过docsite build进行构建，生成对应的html文件，才能推送到仓库中显示。直接修改线上md文件不会有任何效果

**Comment by htynkn** [comment]
@purple-force 感谢回复

1.这个确实是没有直接的关系，如果能够支持确是需要额外的配置
2.我们并没有期望修改md文件直接自动体现到线上网站了。
这个功能更多的用于让用户快速给页面内容提交pr。如果没有相关的支持，目前有办法在模板中获取对应的文件名和相对路径吗？

**Comment by purple-force** [comment]
在项目工程中，在启动docsite或者构建时，会生成md_json的文件夹，这个文件中记录了所有的md相关的信息。其中link字段和文件目录的关系详见 https://docsite.js.org/zh-cn/docs/addDoc.html

**Comment by htynkn** [comment]
> 在项目工程中，在启动docsite或者构建时，会生成md_json的文件夹，这个文件中记录了所有的md相关的信息。其中link字段和文件目录的关系详见 https://docsite.js.org/zh-cn/docs/addDoc.html

感谢，我们这边再调研一下
