### ISSUE TITLE
[Feature Request]: Support Versioning Documentations

### ISSUE THREAD

**Issue by kezhenxu94** [txd-team/docsite#24]
There are many requirements to support versioning documentations: apache/incubator-dubbo-website#293 , mkdocs/mkdocs#193 , and [apache/incubator-skywalking#1360](https://github.com/apache/incubator-skywalking/issues/1360#issuecomment-470933130) .

So I'm wondering whether the txd-team will support versioning doc officially or not?

**Comment by adibrastegarnia** [comment]
@kezhenxu94 @purple-force 
What is the status of this issue? Any plans to support versioniong documentation.
