### ISSUE TITLE
win10运行 npm i -g docsite报错

### ISSUE THREAD

**Issue by TomousLSH** [txd-team/docsite#25]
0 info it worked if it ends with ok
1 verbose cli [ 'G:\\nodejs\\node.exe',
1 verbose cli   'G:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'docsite',
1 verbose cli   '-g' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose npm-session f9f46834fc9c40fe
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/docsite 2930ms
8 silly pacote tag manifest for docsite@latest fetched in 2952ms
9 timing stage:loadCurrentTree Completed in 3124ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule docsite@1.3.8 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-decorators-legacy 420ms
18 silly pacote range manifest for babel-plugin-transform-decorators-legacy@^1.3.4 fetched in 425ms
19 silly resolveWithNewModule babel-plugin-transform-decorators-legacy@1.3.5 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/babel-preset-stage-0 782ms
21 http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-object-rest-spread 885ms
22 http fetch GET 200 https://registry.npmjs.org/asset-require-hook 941ms
23 silly pacote range manifest for asset-require-hook@^1.2.0 fetched in 948ms
24 silly resolveWithNewModule asset-require-hook@1.2.0 checking installable status
25 http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-object-rest-spread/-/babel-plugin-transform-object-rest-spread-6.26.0.tgz 122ms
26 silly pacote range manifest for babel-plugin-transform-object-rest-spread@^6.23.0 fetched in 1012ms
27 silly resolveWithNewModule babel-plugin-transform-object-rest-spread@6.26.0 checking installable status
28 http fetch GET 200 https://registry.npmjs.org/babel-preset-react 1401ms
29 http fetch GET 200 https://registry.npmjs.org/chalk 586ms
30 silly pacote range manifest for chalk@^2.4.1 fetched in 591ms
31 silly resolveWithNewModule chalk@2.4.2 checking installable status
32 http fetch GET 200 https://registry.npmjs.org/babel-preset-react/-/babel-preset-react-6.24.1.tgz 250ms
33 silly pacote range manifest for babel-preset-react@^6.24.1 fetched in 1655ms
34 silly resolveWithNewModule babel-preset-react@6.24.1 checking installable status
35 http fetch GET 200 https://registry.npmjs.org/babel-register 1373ms
36 http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-class-properties 1806ms
37 http fetch GET 200 https://registry.npmjs.org/chokidar 862ms
38 silly pacote range manifest for chokidar@^2.0.3 fetched in 869ms
39 silly resolveWithNewModule chokidar@2.1.2 checking installable status
40 http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-class-properties/-/babel-plugin-transform-class-properties-6.24.1.tgz 115ms
41 silly pacote range manifest for babel-plugin-transform-class-properties@^6.24.1 fetched in 1926ms
42 silly resolveWithNewModule babel-plugin-transform-class-properties@6.24.1 checking installable status
43 http fetch GET 200 https://registry.npmjs.org/babel-register/-/babel-register-6.26.0.tgz 182ms
44 silly pacote range manifest for babel-register@^6.26.0 fetched in 1560ms
45 silly resolveWithNewModule babel-register@6.26.0 checking installable status
46 http fetch GET 200 https://registry.npmjs.org/babel-preset-stage-0/-/babel-preset-stage-0-6.22.0.tgz 1321ms
47 silly pacote version manifest for babel-preset-stage-0@6.22.0 fetched in 2109ms
48 silly resolveWithNewModule babel-preset-stage-0@6.22.0 checking installable status
49 http fetch GET 200 https://registry.npmjs.org/co 787ms
50 silly pacote range manifest for co@^4.6.0 fetched in 793ms
51 silly resolveWithNewModule co@4.6.0 checking installable status
52 http fetch GET 200 https://registry.npmjs.org/ejs 617ms
53 silly pacote range manifest for ejs@^2.6.1 fetched in 622ms
54 silly resolveWithNewModule ejs@2.6.1 checking installable status
55 http fetch GET 200 https://registry.npmjs.org/fs-extra 846ms
56 silly pacote range manifest for fs-extra@^6.0.1 fetched in 853ms
57 silly resolveWithNewModule fs-extra@6.0.1 checking installable status
58 http fetch GET 200 https://registry.npmjs.org/commander 1409ms
59 silly pacote range manifest for commander@^2.15.1 fetched in 1414ms
60 silly resolveWithNewModule commander@2.19.0 checking installable status
61 http fetch GET 200 https://registry.npmjs.org/js-yaml 630ms
62 silly pacote range manifest for js-yaml@^3.12.0 fetched in 637ms
63 silly resolveWithNewModule js-yaml@3.12.2 checking installable status
64 http fetch GET 200 https://registry.npmjs.org/css-modules-require-hook 1487ms
65 silly pacote range manifest for css-modules-require-hook@^4.2.3 fetched in 1492ms
66 silly resolveWithNewModule css-modules-require-hook@4.2.3 checking installable status
67 http fetch GET 200 https://registry.npmjs.org/highlight.js 1344ms
68 silly pacote range manifest for highlight.js@^9.12.0 fetched in 1351ms
69 silly resolveWithNewModule highlight.js@9.15.6 checking installable status
70 http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-runtime 3620ms
71 http fetch GET 200 https://registry.npmjs.org/markdown-it 580ms
72 silly pacote range manifest for markdown-it@^8.4.1 fetched in 584ms
73 silly resolveWithNewModule markdown-it@8.4.2 checking installable status
74 http fetch GET 200 https://registry.npmjs.org/markdown-it-footnote 834ms
75 silly pacote range manifest for markdown-it-footnote@^3.0.1 fetched in 841ms
76 silly resolveWithNewModule markdown-it-footnote@3.0.1 checking installable status
77 http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-object-assign 4156ms
78 http fetch GET 200 https://registry.npmjs.org/markdown-it-github-preamble 862ms
79 silly pacote range manifest for markdown-it-github-preamble@^1.0.0 fetched in 866ms
80 silly resolveWithNewModule markdown-it-github-preamble@1.0.0 checking installable status
81 http fetch GET 200 https://registry.npmjs.org/markdown-it-link-attributes 902ms
82 silly pacote range manifest for markdown-it-link-attributes@^2.0.0 fetched in 907ms
83 silly resolveWithNewModule markdown-it-link-attributes@2.1.0 checking installable status
84 http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-runtime/-/babel-plugin-transform-runtime-6.23.0.tgz 1368ms
85 silly pacote range manifest for babel-plugin-transform-runtime@^6.23.0 fetched in 4993ms
86 silly resolveWithNewModule babel-plugin-transform-runtime@6.23.0 checking installable status
87 http fetch GET 200 https://registry.npmjs.org/opencollective 172ms
88 silly pacote range manifest for opencollective@^1.0.3 fetched in 176ms
89 silly resolveWithNewModule opencollective@1.0.3 checking installable status
90 http fetch GET 200 https://registry.npmjs.org/inquirer 3023ms
91 silly pacote range manifest for inquirer@^6.2.1 fetched in 3028ms
92 silly resolveWithNewModule inquirer@6.2.2 checking installable status
93 http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-object-assign/-/babel-plugin-transform-object-assign-6.22.0.tgz 1343ms
94 silly pacote range manifest for babel-plugin-transform-object-assign@^6.22.0 fetched in 5504ms
95 silly resolveWithNewModule babel-plugin-transform-object-assign@6.22.0 checking installable status
96 http fetch GET 200 https://registry.npmjs.org/markdown-it-katex 1932ms
97 silly pacote range manifest for markdown-it-katex@^2.0.3 fetched in 1937ms
98 silly resolveWithNewModule markdown-it-katex@2.0.3 checking installable status
99 http fetch GET 200 https://registry.npmjs.org/babel-polyfill 5609ms
100 http fetch GET 200 https://registry.npmjs.org/shelljs 336ms
101 silly pacote range manifest for shelljs@^0.8.2 fetched in 342ms
102 silly resolveWithNewModule shelljs@0.8.3 checking installable status
103 http fetch GET 200 https://registry.npmjs.org/react-dom 971ms
104 silly pacote range manifest for react-dom@^16.5.2 fetched in 977ms
105 silly resolveWithNewModule react-dom@16.8.4 checking installable status
106 http fetch GET 200 https://registry.npmjs.org/babel-polyfill/-/babel-polyfill-6.26.0.tgz 1716ms
107 silly pacote range manifest for babel-polyfill@^6.26.0 fetched in 7330ms
108 silly resolveWithNewModule babel-polyfill@6.26.0 checking installable status
109 http fetch GET 200 https://registry.npmjs.org/opencollective-postinstall 2763ms
110 silly pacote range manifest for opencollective-postinstall@^2.0.1 fetched in 2767ms
111 silly resolveWithNewModule opencollective-postinstall@2.0.2 checking installable status
112 http fetch GET 200 https://registry.npmjs.org/babel-preset-es2015 9243ms
113 http fetch GET 200 https://registry.npmjs.org/jsdom 6714ms
114 silly pacote range manifest for jsdom@^11.12.0 fetched in 6725ms
115 silly resolveWithNewModule jsdom@11.12.0 checking installable status
116 http fetch GET 200 https://registry.npmjs.org/babel-preset-es2015/-/babel-preset-es2015-6.22.0.tgz 645ms
117 silly pacote version manifest for babel-preset-es2015@6.22.0 fetched in 9894ms
118 warn deprecated babel-preset-es2015@6.22.0: ðŸ™Œ  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
119 silly resolveWithNewModule babel-preset-es2015@6.22.0 checking installable status
120 http fetch GET 200 https://registry.npmjs.org/markdown-it-replace-link 6023ms
121 silly pacote range manifest for markdown-it-replace-link@^1.0.1 fetched in 6027ms
122 silly resolveWithNewModule markdown-it-replace-link@1.0.1 checking installable status
123 http fetch GET 200 https://registry.npmjs.org/react 4940ms
124 silly pacote range manifest for react@^16.5.2 fetched in 4947ms
125 silly resolveWithNewModule react@16.8.4 checking installable status
126 http fetch GET 200 https://registry.npmjs.org/markdown-it-github-toc 9904ms
127 silly pacote range manifest for markdown-it-github-toc@^3.2.4 fetched in 9909ms
128 silly resolveWithNewModule markdown-it-github-toc@3.2.4 checking installable status
129 http fetch GET 200 https://registry.npmjs.org/node-sass 18960ms
130 silly fetchPackageMetaData error for node-sass@^4.9.2 Unexpected end of JSON input while parsing near '...odash.assign":"^4.2.0'
131 timing stage:rollbackFailedOptional Completed in 0ms
132 timing stage:runTopLevelLifecycles Completed in 27043ms
133 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...odash.assign":"^4.2.0'
133 verbose stack     at JSON.parse (<anonymous>)
133 verbose stack     at parseJson (G:\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
133 verbose stack     at consumeBody.call.then.buffer (G:\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
133 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
134 verbose cwd C:\Users\Administrator
135 verbose Windows_NT 10.0.14393
136 verbose argv "G:\\nodejs\\node.exe" "G:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "docsite" "-g"
137 verbose node v10.15.3
138 verbose npm  v6.4.1
139 error Unexpected end of JSON input while parsing near '...odash.assign":"^4.2.0'
140 verbose exit [ 1, true ]

**Comment by purple-force** [comment]
第139行的信息可以提供完整一点吗？

**Comment by PG123GG** [comment]
> 137 verbose node v10.15.3
> 138 verbose npm v6.4.1

这个解决了吗，兄弟

**Comment by x-cold** [comment]
```bash
npm uninstall -g docsite
npm i -g docsite --registry=https://registry.npm.taobao.org
```

**Comment by PG123GG** [comment]
> ```shell
> npm i -g docsite --registry=https://registry.npm.taobao.org
> ```
使用这个命令安装，202状态码变成304，可以安装成功。有下面的日志

npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pg\AppData\Roaming\npm-cache\_logs\2019-04-19T11_48_48_351Z-debug.log

而且在docsite start时报错
(node:8316) UnhandledPromiseRejectionWarning: ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "D:\\docsite\\.babelrc" at 0, attempted to resolve relative to "D:\\docsite"
    at C:\Users\pg\AppData\Roaming\npm\node_modules\docsite\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\pg\AppData\Roaming\npm\node_modules\docsite\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\pg\AppData\Roaming\npm\node_modules\docsite\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\pg\AppData\Roaming\npm\node_modules\docsite\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Users\pg\AppData\Roaming\npm\node_modules\docsite\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\pg\AppData\Roaming\npm\node_modules\docsite\node_modules\babel-register\lib\node.js:144:14)

**Comment by x-cold** [comment]
这个也是依赖没有安装好的问题，建议全局设置一下 npm 的 registry 

```bash
npm config set registry https://registry.npm.taobao.org 
```
