### ISSUE TITLE
centos7安装报错

### ISSUE THREAD

**Issue by 1315861791** [txd-team/docsite#26]
![image](https://user-images.githubusercontent.com/24642133/56880499-94279380-6a8f-11e9-824e-c54af813c6fa.png)
安装命令如下
npm install docsite -g

**Comment by purple-force** [comment]
应该是系统权限问题，在线查找下相关的解决办法

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/56881488-25e4d000-6a93-11e9-9efa-bdb9166acec4.png)
再请教一下，这个情况是没安装成功吗？

**Comment by purple-force** [comment]
是全局安装的吗？

**Comment by 1315861791** [comment]
是的： sudo npm install -f  docsite -g

**Comment by purple-force** [comment]
执行 which docsite看是否能找到安装位置

**Comment by 1315861791** [comment]
似乎找不到，输出是这样的;/usr/bin/which: no docsite in (/opt/jdk1.8.0_191/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

**Comment by purple-force** [comment]
执行 sudo npm install docsite -g 试试

**Comment by 1315861791** [comment]
![image](https://user-images.githubusercontent.com/24642133/56882109-3433eb80-6a95-11e9-9d83-28519e827c5d.png)

**Comment by purple-force** [comment]
https://blog.csdn.net/young_Emily/article/details/79038545
你按照这个试试看

**Comment by 1315861791** [comment]
好的，谢谢

**Comment by 1315861791** [comment]
一波操作以后，还报错，但版本号能打印出来，是成功了还是失败了
![image](https://user-images.githubusercontent.com/24642133/56883995-f3d76c00-6a9a-11e9-9c8b-60df108a8cf2.png)

**Comment by 1315861791** [comment]
我在docker容器（centos7操作系统）中也试了，报错跟云主机一样

**Comment by 1315861791** [comment]
我在docker容器中试着安装，也报错，如下：
![image](https://user-images.githubusercontent.com/24642133/56884195-968fea80-6a9b-11e9-8f62-4735e28e517c.png)

**Comment by 1315861791** [comment]
搞得我脑仁疼，麻烦问一下这个镜像是官方的吗？我直接下载镜像得了
![image](https://user-images.githubusercontent.com/24642133/56889675-9860aa80-6aa9-11e9-853b-fa296d1aa1d2.png)

**Comment by purple-force** [comment]
docsite是npm包，不存在镜像的概念。你看到的这个错误是需要的依赖node-sass安装的问题，只能再试试这些了 https://segmentfault.com/a/1190000012912618、https://segmentfault.com/a/1190000010984731

**Comment by leeyongda** [comment]
sudo npm install docsite -g --unsafe-perm
// 试下是否能解决你的安装依赖问题。
