### ISSUE TITLE
发布站点docsite到github,操作「Docsite build 」生成哪些文件要放置在github?

### ISSUE THREAD

**Issue by jingmi-vip** [txd-team/docsite#27]
发布站点docsite到github,操作「Docsite build 」生成哪些文件要放置在github?

“官方文档：「服务器托管」
将项目中的build目录、img目录、zh-cn目录、en-us目录、index.html及其他图片资源放置在服务器中即可。”

我就是这样做的把「build目录、img目录、zh-cn目录、en-us目录、index.html」部署到了github上有问题，我的项目：https://jingmi-vip.github.io/doc_test/

**Comment by purple-force** [comment]
看下这里 https://docsite.js.org/zh-cn/docs/path.html
