### ISSUE TITLE
部署docsite 到github,访问跳转有问题？求大神指导？

### ISSUE THREAD

**Issue by jingmi-vip** [txd-team/docsite#28]
项目 [https://github.com/jingmi-vip/doc_test.git](https://github.com/jingmi-vip/doc_test.git)
访问地址：[https://jingmi-vip.github.io/doc_test/](https://jingmi-vip.github.io/doc_test/)
部署docsite 到github,访问跳转有问题？求大神指导？

@purple-force

**Comment by purple-force** [comment]
看下这里 https://docsite.js.org/zh-cn/docs/path.html
