### ISSUE TITLE
意外发现，是否是广告植入？

### ISSUE THREAD

**Issue by JefferyTest** [txd-team/docsite#31]
如题，在md文件中，添加以下文字   

       - **eureka.name**：服务注册名称    

渲染后的页面视图增加 `a` 标签，点击后跳转到 https://eureka.name/ 个人网站，是有意为之？还是别的原因？

**Comment by purple-force** [comment]
还有这效果？

**Comment by x-cold** [comment]
这是 markdown 的自动 link 效果。eureka.name 被识别为 url 了，跟 docsite 无关哦~
