### ISSUE TITLE
页面内瞄点跳转

### ISSUE THREAD

**Issue by JefferyTest** [txd-team/docsite#33]
查看 [NACOS_FAQ](https://nacos.io/zh-cn/docs/FAQ.html) 页面，点击链接是可以进行跳转到指定的位置，查看DOM元素，发现有个id，但是markdown语法里面的`.`是可以忽略的，亦或者是需要自己在md文件手写跳转id ?

       ## <h2 id='2.3'>2.3 bootstrap</h2>

尝试着手写id，但是渲染后的HTML元素多了一个空的`h4`，并且多了一条横线。

![222](https://user-images.githubusercontent.com/33674804/58170024-ed689880-7cc4-11e9-84ca-03985f69ce13.png)

查看github上面的语法好像是另外一种写法，例如[Apollo配置中心介绍](https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E4%BB%8B%E7%BB%8D)，写法如下（部分）：

       * [1、What is Apollo](#1what-is-apollo)
       * [2、Why Apollo](#2why-apollo)
       * [3、Apollo at a glance](#3apollo-at-a-glance)
       * [4、Apollo in depth](#4apollo-in-depth)
       * [5、Contribute to Apollo](#5contribute-to-apollo)

       # 1、What is Apollo

       ## 1.1 背景

       ## 1.2 Apollo简介

       # 2、Why Apollo
想知道nacos 上面的链接是怎么写的？

**Comment by purple-force** [comment]
![image](https://user-images.githubusercontent.com/16146970/58171197-00309c80-7cc8-11e9-9cbe-a4671fb2c751.png)
![image](https://user-images.githubusercontent.com/16146970/58171213-09ba0480-7cc8-11e9-9e77-70f231b3de2d.png)

**Comment by JefferyTest** [comment]
@purple-force 我也是这么写的，但是多了一条横线是怎么处理的？

**Comment by purple-force** [comment]
![image](https://user-images.githubusercontent.com/16146970/58173073-f198b400-7ccc-11e9-8668-b2094e872c71.png)
前面多了两个##

**Comment by JefferyTest** [comment]
> ![image](https://user-images.githubusercontent.com/16146970/58173073-f198b400-7ccc-11e9-8668-b2094e872c71.png)
> 前面多了两个##

哦，疏忽了，多谢
