### ISSUE TITLE
不支持Node 8.X吗？

### ISSUE THREAD

**Issue by ScnuWang** [txd-team/docsite#34]
![image](https://user-images.githubusercontent.com/14845527/58886113-f0787580-8715-11e9-9b3e-f9b0896413b9.png)
![image](https://user-images.githubusercontent.com/14845527/58886174-08e89000-8716-11e9-9a98-8a1d7b57bd88.png)

**Comment by purple-force** [comment]
先按照错误提示执行`npm rebuild node-sass`，如果还不行。删除掉项目下的所有依赖，重新执行`npm i`安装依赖后再试试
