### ISSUE TITLE
[疑问] build 命令是否支持生成到目录

### ISSUE THREAD

**Issue by htynkn** [txd-team/docsite#35]
你好，

关于Docsite的使用，在运行
`docsite build` 之后会生成文件在当前目录，生成文件和源文件混杂在一起，不是很好管理和部署。

想询问一下是否支持将文件生成到一个指定目录（也许可以指定目录），然后直接部署那个目录内所有文件就行了。

比如hugo是生成到public目录 （https://gohugo.io/getting-started/usage/）

**Comment by htynkn** [comment]
该功能可以减少类似询问：https://github.com/txd-team/docsite/issues/27

**Comment by purple-force** [comment]
由于有语言切换的功能，且语言版本体现在url当中。对于静态访问的站点，url即对应着实际的文件目录。
需要部署的文件见 https://docsite.js.org/zh-cn/docs/publish.html

**Comment by htynkn** [comment]
感谢回复
