### ISSUE TITLE
首页的logo以及ico该怎么修改？

### ISSUE THREAD

**Issue by hengboy** [txd-team/docsite#37]
首页的白色、彩色、灰色的logo该怎么修改？
怎么添加ico图标？

**Comment by purple-force** [comment]
白色和彩色的logo在这里
![image](https://user-images.githubusercontent.com/16146970/60644833-c8417b00-9e69-11e9-9e6c-60c8a488c601.png)
![image](https://user-images.githubusercontent.com/16146970/60644863-dabbb480-9e69-11e9-91eb-fbfc36aaba41.png)
底部的灰色在每个页面文件对应的这里
![image](https://user-images.githubusercontent.com/16146970/60644916-f2933880-9e69-11e9-9ebe-2cf6dda4a081.png)

ico图标
![image](https://user-images.githubusercontent.com/16146970/60644968-10609d80-9e6a-11e9-8fc2-c1741f62b1a3.png)
![image](https://user-images.githubusercontent.com/16146970/60644993-20787d00-9e6a-11e9-8128-0b4f1e9df5ed.png)
