### ISSUE TITLE
什么时候博客支持评论和数据展示？

### ISSUE THREAD

**Issue by yicm** [txd-team/docsite#41]

**Comment by x-cold** [comment]
没有计划支持呢，亲可以考虑使用市面常用的畅言，disqus 之类的工具来支持社会化（评论）

至于数据展示部分，可以说说具体的需求吗

**Comment by lovepoem** [comment]
参考 https://github.com/wuhan2020/wuhan2020.github.io  ，已经自行支持Gitalk
