### ISSUE TITLE
mac s上 docsite start 报错

### ISSUE THREAD

**Issue by HakChealKim** [txd-team/docsite#46]
报错 stack trace：
`const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/xuezhe.jin/sideProject/daily/daily/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/xuezhe.jin/sideProject/daily/daily/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/xuezhe.jin/sideProject/daily/daily/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.require.extensions.<computed> [as .js] (/Users/xuezhe.jin/sideProject/daily/daily/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
^C`

**Comment by HakChealKim** [comment]
.babelrc
`{
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-object-rest-spread",
    "transform-object-assign",
    [
      "transform-runtime",
      {
        "helpers": false,
        "polyfill": false,
        "regenerator": true,
        "moduleName": "babel-runtime"
      }
    ]
  ],
  "presets": [
    "react",
    "stage-0",
    "es2015"
  ]
}
`

**Comment by HakChealKim** [comment]
package.json
`{
  "name": "site",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "docsite start",
    "build": "docsite build"
  },
  "devDependencies": {
    "docsite": "^1.1.0",
    "babel-core": "6.23.1",
    "babel-eslint": "^6.0.5",
    "babel-loader": "6.4.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "6.22.0",
    "babel-preset-react": "6.23.0",
    "babel-preset-stage-0": "6.22.0",
    "babel-register": "^6.26.0",
    "css-loader": "0.6.12",
    "eslint": "^3.6.0",
    "eslint-config-ali": "^1.0.0",
    "eslint-plugin-import": "*",
    "eslint-plugin-react": "*",
    "extract-text-webpack-plugin": "^2.1.2",
    "gulp": "3.9.1",
    "gulp-util": "2.2.20",
    "json-loader": "*",
    "node-libs-browser": "2.0.0",
    "node-sass": "^4.7.2",
    "opn": "^5.3.0",
    "raw-loader": "^0.5.1",
    "react": "16.5.2",
    "react-dom": "16.5.2",
    "sass-loader": "6.0.2",
    "style-loader": "0.6.5",
    "webpack": "^2.6.1",
    "webpack-dev-server": "^2.4.5"
  },
  "dependencies": {
    "classnames": "^2.2.5",
    "core-decorators": "^0.20.0",
    "js-cookie": "^2.2.0",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-scroll": "^1.7.9",
    "react-tilt": "^0.1.4",
    "whatwg-fetch": "^2.0.4"
  }
}
`
webpack.config.js
`const path = require('path');
const fs = require('fs');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const entry = {};
const targetPath = path.join(__dirname, './src/pages');
fs.readdirSync(targetPath).forEach(page => {
  if (
    fs.statSync(path.join(targetPath, page)).isDirectory() &&
    fs.existsSync(path.join(targetPath, page, 'index.jsx'))
  ) {
    entry[page] = path.join(targetPath, page, 'index.jsx');
  }
});
module.exports = {
  entry,
  output: {
    path: path.join(__dirname, 'build'),
    filename: '[name].js',
  },
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  },
  module: {
    loaders: [
      {
        test: /\.js|jsx$/,
        exclude: [/node_modules/, /build\/lib/, /\.min\.js$/],
        use: 'babel-loader',
      },
      {
        test: /\.(s)?css$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader'],
        }),
      },
      {
        test: /\.json?$/,
        exclude: /node_modules/,
        use: 'json-loader',
      },
    ],
  },
  resolve: {
    extensions: ['.js', '.jsx', '.json'],
  },
  plugins: [
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new ExtractTextPlugin('[name].css'),
  ],
};
`

**Comment by HakChealKim** [comment]
降到node10
好了

**Comment by ryshi** [comment]
遇到同样问题，只能降级node么？搜到一个类似[问题](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node) 说是node 12 和 gulp 4冲突，是否可以考虑升级？
