### ISSUE TITLE
首页按钮只能2个吗

### ISSUE THREAD

**Issue by mysad** [txd-team/docsite#48]
想首页加三个菜单，立即查看，github，gitee

home.jsx:buttons多加了一个菜单，但是还是显示2个菜单

找到page/home/index.jsx

dataSource.brand.buttons.map(b => <Button type={b.type} key={b.type} link={b.link} target={b.target}>{b.text}</Button>)
{   console.log(dataSource.brand.buttons)}

打印数据是3个
如何才能设置3个菜单？

**Comment by purple-force** [comment]
推荐是最多两个。你看下是不是因为样式的原因。

**Comment by hengboy** [comment]
@mysad 
```
dataSource.brand.buttons.map(b => <Button type={b.type} key={b.type} link={b.link} target={b.target}>{b.text}</Button>)
```
改为：
```
dataSource.brand.buttons.map(b => <Button type={b.type} link={b.link} target={b.target}>{b.text}</Button>)
```

> 将 `key={b.type}` 去掉，key是唯一标识，如果按钮的类型都为'normal'，则只会显示最后一个，会把之前的替换掉
