### ISSUE TITLE
win10 local preview error

### ISSUE THREAD

**Issue by ns2250225** [txd-team/docsite#5]
environment:
win10
nodev8.9.4

when run command in powershell :  docsite start
get this:
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
exec: 'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by purple-force** [comment]
could you plz provide the detail info instead of gibberish? 
https://www.zhihu.com/question/54724102

**Comment by ns2250225** [comment]
@purple-force sorry for that，i get this:
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
exec: 'node_modules' is not recognized as an internal or external command,
operable program or batch file.
