### ISSUE TITLE
'docsite' 不是内部或外部命令

### ISSUE THREAD

**Issue by samz406** [txd-team/docsite#59]
你好，我本地node版本为 v10.15.3
安装过程如下，但是执行 docsite -V，报不是内部或外部命令，对node不是很熟悉，麻烦看看。

![QQ截图20191214235917](https://user-images.githubusercontent.com/3055810/70851249-c9251100-1ecd-11ea-8e5e-4964688e72aa.png)

**Comment by purple-force** [comment]
参照下这里设置下环境变量 https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows/9588052#9588052
