### ISSUE TITLE
请问为什么在本地网站可以跑起来，但是搭载github格式就全乱了?

### ISSUE THREAD

**Issue by chengtianyue** [txd-team/docsite#65]
如题，我的网站是chengtianyue.github.io，项目地址是https://github.com/chengtianyue/chengtianyue.github.io，之前一直是按照教程做的。

**Comment by purple-force** [comment]
![image](https://user-images.githubusercontent.com/16146970/74101685-8606b780-4b77-11ea-982d-3944206f6d10.png)
请注意一下注释说明

**Comment by purple-force** [comment]
https://docsite.js.org/zh-cn/docs/path.html

**Comment by chengtianyue** [comment]
哦哦那个github好像得过几分钟才能看到修改过的，现在没问题了！感谢您
