### ISSUE TITLE
如何让首页显示自定义标题？而不是只显示 <title>home</title> ？

### ISSUE THREAD

**Issue by ghw** [txd-team/docsite#9]
如何让首页显示自定义标题？而不是只显示 <title>home</title> ？

https://nacos.io/zh-cn/

谢谢

**Comment by purple-force** [comment]
目前在寻找一个合适的放置该配置项的地方

**Comment by ghw** [comment]
这个放site.js能实现嘛

**Comment by purple-force** [comment]
升级docsite至1.3.3，具体看下这个 https://docsite.js.org/zh-cn/docs/SEO.html
